// <auto-generated />
namespace TestTask.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NextId_index : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NextId_index));
        
        string IMigrationMetadata.Id
        {
            get { return "201906012056530_NextId_index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
